spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082